import sqlite3
import os
from datetime import datetime

from werkzeug.security import generate_password_hash

DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "wound_database.db")

def get_db_connection():
    """
    Establishes and returns an SQLite database connection.
    Enables dictionary row factory for column-name keyed indexing.
    """
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    """
    Initializes the SQLite tables (users, reports) if they do not already exist.
    Inserts a default admin account if not already present.
    """
    # Ensure the parent directory exists
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    
    conn = get_db_connection()
    cursor = conn.cursor()
    
    # 1. Create Users Table
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT UNIQUE NOT NULL,
            email TEXT NOT NULL,
            password_hash TEXT NOT NULL,
            role TEXT DEFAULT 'user',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    
    # 2. Create Reports Table
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS reports (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            filename TEXT NOT NULL,
            wound_type TEXT NOT NULL,
            severity TEXT NOT NULL,
            major_minor TEXT NOT NULL,
            infection_possibility TEXT NOT NULL,
            emergency_level TEXT NOT NULL,
            confidence REAL NOT NULL,
            first_aid TEXT NOT NULL,
            red_pixel_count INTEGER DEFAULT 0,
            redness_ratio REAL DEFAULT 0.0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
        )
    """)
    
    # Check if a default admin exists; if not, create a seed one
    # Note: Flask app will handle registration, but we initialize a seed user/admin shell if empty.
    cursor.execute("SELECT COUNT(*) FROM users WHERE role = 'admin'")
    if cursor.fetchone()[0] == 0:
        # Default admin credentials: username 'admin', email 'admin@woundai.com'
        # Password hash is generated by Werkzeug security for 'admin123'
        admin_hash = generate_password_hash("admin123")
        try:
            cursor.execute("""
                INSERT INTO users (username, email, password_hash, role)
                VALUES ('admin', 'admin@woundai.com', ?, 'admin')
            """, (admin_hash,))
            print("[Database] Seeded default admin account (username: admin, password: admin123)")
        except sqlite3.IntegrityError:
            pass

    conn.commit()
    conn.close()
    print("[Database] SQLite Tables verified and initialized.")

# ==========================================
# User Account Queries
# ==========================================

def register_user(username, email, password_hash, role='user'):
    """Inserts a new user record. Returns True on success, False if username taken."""
    conn = get_db_connection()
    cursor = conn.cursor()
    success = False
    try:
        cursor.execute("""
            INSERT INTO users (username, email, password_hash, role)
            VALUES (?, ?, ?, ?)
        """, (username, email, password_hash, role))
        conn.commit()
        success = True
    except sqlite3.IntegrityError:
        success = False
    finally:
        conn.close()
    return success

def get_user_by_username(username):
    """Retrieves a user row dictionary matching the specified username."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM users WHERE username = ?", (username,))
    row = cursor.fetchone()
    conn.close()
    return row

def get_user_by_id(user_id):
    """Retrieves a user row dictionary matching the specified ID."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM users WHERE id = ?", (user_id,))
    row = cursor.fetchone()
    conn.close()
    return row

def get_all_users():
    """Retrieves list of all users ordered by creation date."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT id, username, email, role, created_at FROM users ORDER BY id DESC")
    rows = cursor.fetchall()
    conn.close()
    return rows

# ==========================================
# Diagnostic Report Queries
# ==========================================

def add_report(user_id, filename, wound_type, severity, major_minor, 
               infection_possibility, emergency_level, confidence, first_aid,
               red_pixel_count=0, redness_ratio=0.0):
    """Saves a wound detection report record to the database."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO reports (
            user_id, filename, wound_type, severity, major_minor,
            infection_possibility, emergency_level, confidence, first_aid,
            red_pixel_count, redness_ratio
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (user_id, filename, wound_type, severity, major_minor,
          infection_possibility, emergency_level, confidence, first_aid,
          red_pixel_count, redness_ratio))
    report_id = cursor.lastrowid
    conn.commit()
    conn.close()
    return report_id

def get_reports_by_user_id(user_id):
    """Fetches diagnostic history records for a specific patient."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT * FROM reports 
        WHERE user_id = ? 
        ORDER BY created_at DESC
    """, (user_id,))
    rows = cursor.fetchall()
    conn.close()
    return rows

def get_all_reports():
    """Fetches all reports in the database, with joined username, for administrators."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT reports.*, users.username 
        FROM reports
        JOIN users ON reports.user_id = users.id
        ORDER BY reports.created_at DESC
    """)
    rows = cursor.fetchall()
    conn.close()
    return rows

def get_report_by_id(report_id):
    """Retrieves a single report details by its ID."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("""
        SELECT reports.*, users.username 
        FROM reports
        JOIN users ON reports.user_id = users.id
        WHERE reports.id = ?
    """, (report_id,))
    row = cursor.fetchone()
    conn.close()
    return row

def delete_report(report_id):
    """Deletes a specific report by ID."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("DELETE FROM reports WHERE id = ?", (report_id,))
    conn.commit()
    conn.close()
    return True

# ==========================================
# Analytical Dashboard Queries
# ==========================================

def get_dashboard_stats():
    """Compiles key statistical aggregates for user dashboards."""
    conn = get_db_connection()
    cursor = conn.cursor()
    
    stats = {}
    
    # Total patients / reports
    cursor.execute("SELECT COUNT(*) FROM users")
    stats["total_users"] = cursor.fetchone()[0]
    
    cursor.execute("SELECT COUNT(*) FROM reports")
    stats["total_reports"] = cursor.fetchone()[0]
    
    # Severity split
    cursor.execute("SELECT COUNT(*) FROM reports WHERE major_minor = 'Major'")
    stats["major_count"] = cursor.fetchone()[0]
    
    cursor.execute("SELECT COUNT(*) FROM reports WHERE major_minor = 'Minor'")
    stats["minor_count"] = cursor.fetchone()[0]
    
    # Infection status
    cursor.execute("SELECT COUNT(*) FROM reports WHERE infection_possibility = 'High'")
    stats["high_infection_count"] = cursor.fetchone()[0]
    
    # Average confidence
    cursor.execute("SELECT AVG(confidence) FROM reports")
    avg_conf = cursor.fetchone()[0]
    stats["avg_confidence"] = round(avg_conf, 1) if avg_conf else 0.0
    
    # Wound type counts
    cursor.execute("SELECT wound_type, COUNT(*) as cnt FROM reports GROUP BY wound_type")
    wound_types = cursor.fetchall()
    stats["wound_distribution"] = {row["wound_type"]: row["cnt"] for row in wound_types}
    
    # Emergency levels count
    cursor.execute("SELECT emergency_level, COUNT(*) as cnt FROM reports GROUP BY emergency_level")
    em_levels = cursor.fetchall()
    stats["emergency_distribution"] = {row["emergency_level"]: row["cnt"] for row in em_levels}
    
    conn.close()
    return stats
